services:
  
  db_dev:
    image: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data_dev/
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data_dev: