services:

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - ./.env.prod.api
    expose:
      - "5000"
    depends_on:
      - db

  web_app:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: gunicorn up_route_web_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    env_file:
      - ./.env.prod
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web_app

volumes:
  postgres_data:
  static_volume: