# Generated by Django 5.1.1 on 2024-10-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressCollection',
            new_name='RouteParametersModel',
        ),
    ]
