# Generated by Django 5.1.1 on 2024-10-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
