version: '3.9'
services:
  web:
    build: .
    command: gunicorn up_route_web_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - sqlite_data:/app/db.sqlite3
    ports:
      - "8000:8000"

volumes:
  sqlite_data: